#!/usr/bin/perl
use strict;
use warnings;

# Run the brightnessctl command to get the current and max brightness
my $brightness = `brightnessctl get`;
chomp($brightness);
my $max_brightness = `brightnessctl max`;
chomp($max_brightness);

# Calculate the percentage
my $percentage = ($brightness / $max_brightness) * 100;
$percentage = sprintf("%.0f", $percentage);  

# Print the current brightness
print "$percentage%\n";

