[env]
TERM = "xterm-256color"

[font]
size = 18.0

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[window]
startup_mode = 'Maximized'
dynamic_padding = true
padding = { x = 0, y = 0 }

# Default colors
[colors.primary]
background =  '#ffffea'
foreground =  '#000000'

# Normal colors
[colors.normal]
black   = '#101010'
red     = '#af5f00'
green   = '#cccc7c'
yellow  = '#ffff5f'
blue    = '#aeeeee'
magenta = '#505050'
cyan    = '#afffd7'
white   = '#fcfcce'

# Bright colors
[colors.bright]
black   = '#101010'
red     = '#af5f00'
green   = '#cccc7c'
yellow  = '#ffff5f'
blue    = '#aeeeee'
magenta = '#505050'
cyan    = '#afffd7'
white   = '#fcfcce'
